version: '3.8'
networks:
  cold:
    external: true
services:
  proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.10
    networks:
      - cold
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "-api.insecure=true"
      - "--providers.docker=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.rule=Host(`www.coldclimate.wtf`)"
      - "traefik.http.routers.proxy.entrypoints=web"
      - "traefik.entryPoints.web.address=:80"
      - "traefik.entryPoints.websecure.address=:443"
      - "traefik.entryPoints.tcp.address=:5432"
    ports:
      - "80:80"
      - "443:443"
      - "4200:4200"
      - "4400:4400"
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  rabbit:
    labels:
      - "traefik.http.routers.rabbit.rule=Host(`rabbit.coldclimate.wtf`)"
      - "traefik.tcp.routers.rabbit.rule=Host(`rabbit.coldclimate.wtf`)"
      - "traefik.tcp.services.rabbit.loadbalancer.server.port=5672"
      - "traefik.http.services.rabbit.loadbalancer.server.port=15672"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cold
    depends_on:
      - proxy
    image: rabbitmq:3-management-alpine
    container_name: cold-rabbit
  cache:
    labels:
      - "traefik.http.routers.cache.rule=Host(`cache.coldclimate.wtf`)"
      - "traefik.tcp.services.cache.loadbalancer.server.port=6379"
      - "traefik.udp.services.cache.loadbalancer.server.port=6379"
    image: redis:latest
    container_name: cold-cache
    restart: always
    depends_on:
      - proxy
    networks:
      - cold
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
  postgres:
    container_name: cold-postgres
    image: postgres:14-alpine
    depends_on:
      - proxy
    networks:
      - cold
    ports:
      - '5432:5432'
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=colddb

