version: '3.8'
networks:
  cold:
    external: true
services:
  proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.10
    networks:
      - cold
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "-api.insecure=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.tcp.address=:5432"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.rule=Host(`www.coldclimate.local`)"
      - "traefik.http.routers.proxy.entrypoints=web"
      - "traefik.entryPoints.web.address=:80"
      - "traefik.entryPoints.websecure.address=:443"
      - "traefik.entryPoints.tcp.address=:5432"
    ports:
      - "80:80"
      - "443:443"
      - "4200:4200"
      - "4400:4400"
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  rabbit:
    labels:
      - "traefik.tcp.services.rabbit.loadbalancer.server.port=5672"
      - "traefik.http.services.rabbit.loadbalancer.server.port=15672"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cold
    depends_on:
      - proxy
    image: rabbitmq:3-management-alpine
    container_name: cold-rabbit
  cache:
    labels:
      - "traefik.http.routers.cache.rule=Host(`cache.coldclimate.local`)"
      - "traefik.tcp.services.cache.loadbalancer.server.port=6379"
      - "traefik.udp.services.cache.loadbalancer.server.port=6379"
    image: redis:latest
    container_name: cold-cache
    restart: always
    depends_on:
      - proxy
    networks:
      - cold
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
  postgres:
    container_name: cold-postgres
    image: postgres:14-alpine
    depends_on:
      - proxy
    networks:
      - cold
    ports:
      - '5432:5432'
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=colddb
  graphql:
    build:
      context: .
      dockerfile: _graphql.dockerfile
    container_name: cold-graphql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`graphql.coldclimate.local`)"
      - "traefik.http.routers.api.entrypoints=web"
    restart: always
    networks:
      - cold
    external_links:
      - postgres
      - cache
    depends_on:
      - proxy
      - postgres
    ports:
      - '9001:9001'
    environment:
      AUTH_BASE_URI: http://localhost:9001
      AUTH_JWKS_URI: https://dev-6qt527e13qyo4ls6.us.auth0.com/.well-known/jwks.json
      AUTH_JWT_ALGORITHM: RS256
      AUTH_WHITELIST_DOMAINS: localhost
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/colddb
      NODE_ENV: development
      VITE_AUTH_CLIENT_ID: 7AtWz1WzXMty9QN38zrkfUj2JqxqpiFI
      VITE_AUTH_ZERO_DOMAIN: dev-6qt527e13qyo4ls6us.auth0.com
      AWS_REGION: us-east-1
    volumes:
      - ~/.aws:/root/.aws

