version: '3.8'
networks:
  cold:
    external: true
services:
  proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.10

    networks:
      - cold
    # Enables the web UI and tells Traefik to listen to docker
    restart: always
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
      - "--entryPoints.tcp.address=:5432"
      - "--entryPoints.tcp.address=:5672"
      - "--entryPoints.tcp.address=:15672"
      - "--entryPoints.tcp.address=:6379"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.rule=Host(`proxy.coldclimate.local`)"
      - "traefik.http.routers.proxy.entrypoints=web"
      - "traefik.http.services.proxy.loadbalancer.server.port=8080"
      - "traefik.entryPoints.web.address=:80"
      - "traefik.entryPoints.websecure.address=:443"
      - "traefik.entryPoints.tcp.address=:5432"
      - "traefik.entryPoints.tcp.address=:5672"
      - "traefik.entryPoints.tcp.address=:15672"
      - "traefik.entryPoints.tcp.address=:6379"
    ports:
      - "80:80"
      - "443:443"
      - "4200:4200"
      - "4400:4400"
      - "8080:8080"
    volumes:
      - traefik_data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  n8n:
    build:
      context: .
      dockerfile: _n8n.dockerfile
      args:
        N8N_VERSION: 1.89.2
        DD_ENV: docker
        NODE_ENV: docker
        DD_SERVICE: cold-n8n
        DB_TYPE: postgresdb
        DATABASE_URL: postgres://postgres:postgres@postgres:5432/colddb
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.entrypoints=web,websecure
      - traefik.http.routers.n8n.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.n8n.headers.SSLRedirect=true
      - traefik.http.middlewares.n8n.headers.STSSeconds=315360000
      - traefik.http.middlewares.n8n.headers.browserXSSFilter=true
      - traefik.http.middlewares.n8n.headers.contentTypeNosniff=true
      - traefik.http.middlewares.n8n.headers.forceSTSHeader=true
      - traefik.http.middlewares.n8n.headers.SSLHost=${DOMAIN_NAME}
      - traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.n8n.headers.STSPreload=true
      - traefik.http.routers.n8n.middlewares=n8n@docker
    environment:
      - PGHOST=postgres
      - DB_TYPE=postgresdb
      - DB_TABLE_PREFIX=n8n_
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/colddb
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
    networks:
      - cold
    links:
      - postgres
      - cache
  rabbit:
    labels:
      - "traefik.tcp.routers.rabbit.rule=HostSNI(`rabbit.coldclimate.local`)"
      - "traefik.tcp.routers.rabbit.entrypoints=tcp"
      - "traefik.tcp.routers.rabbit.tls=true"
      - "traefik.tcp.services.rabbit.loadbalancer.server.port=5672"
      - "traefik.http.routers.rabbit-http.rule=Host(`rabbit.coldclimate.local`)"
      - "traefik.http.routers.rabbit-http.entrypoints=web"
      - "traefik.http.services.rabbit-http.loadbalancer.server.port=15672"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cold
    depends_on:
      - proxy
    image: rabbitmq:3-management-alpine
    container_name: cold-rabbit
  cache:
    labels:
      - "traefik.tcp.routers.redis.rule=HostSNI(`cache.coldclimate.local`)"
      - "traefik.tcp.routers.redis.entrypoints=tcp"
      - "traefik.tcp.routers.redis.tls=true"
      - "traefik.tcp.services.redis.loadbalancer.server.port=6379"
    image: redis:latest
    container_name: cold-cache
    restart: always
    depends_on:
      - proxy
    networks:
      - cold
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
  postgres:
    container_name: cold-postgres
    image: postgres:15-alpine
    labels:
      - "traefik.http.routers.postgres.rule=Host(`db.coldclimate.local`)"
      - "traefik.tcp.services.postgres.loadbalancer.server.port=5432"
      - "traefik.udp.services.postgres.loadbalancer.server.port=5432"
    depends_on:
      - proxy
    networks:
      - cold
    ports:
      - '5432:5432'
    volumes:
      - ~/apps/postgres/15:/var/lib/postgresql/15/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=colddb
  graphql:
    build:
      context: .
      dockerfile: _graphql.dockerfile
      args:
        DD_ENV: docker
        NODE_ENV: docker
        DD_SERVICE: cold-graphql
        DATABASE_URL: postgres://postgres:postgres@postgres:5432/colddb
    container_name: cold-graphql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.graphql.rule=Host(`graphql.coldclimate.local`)"
      - "traefik.http.routers.graphql.entrypoints=web"
    restart: always
    networks:
      - cold
    links:
      - postgres
      - cache
    external_links:
      - postgres
      - cache
    depends_on:
      - proxy
      - postgres
    ports:
      - '9001:9001'
    environment:
      AUTH_BASE_URI: http://localhost:9001
      DD_SERVICE: cold-graphql
      AUTH_JWKS_URI: https://dev-6qt527e13qyo4ls6.us.auth0.com/.well-known/jwks.json
      AUTH_JWT_ALGORITHM: RS256
      AUTH_WHITELIST_DOMAINS: localhost
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/colddb
      NODE_ENV: docker
      DD_ENV: docker
      VITE_AUTH_CLIENT_ID: 7AtWz1WzXMty9QN38zrkfUj2JqxqpiFI
      VITE_AUTH_ZERO_DOMAIN: dev-6qt527e13qyo4ls6us.auth0.com
      AWS_REGION: us-east-1
    volumes:
      - ~/.aws:/root/.aws
  api:
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    build:
      context: .
      dockerfile: _api_local.dockerfile
      args:
        NODE_ENV: docker
        DD_ENV: docker
        DD_SERVICE: cold-api
        DD_VERSION: 99.99.99
        DATABASE_URL: postgres://postgres:postgres@host.docker.internal:5432/colddb
        DD_POSTGRES_PASSWORD: emanate-rail-pliable-brindled-plea-PADDOCK
        DD_API_KEY: ${DD_API_KEY}
        FC_GIT_COMMIT_SHA: cdc3b19
    container_name: cold-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.coldclimate.local`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=7001"
    restart: always
    networks:
      - cold
    links:
      - postgres
      - rabbit
      - cache
    external_links:
      - postgres
      - rabbit
      - cache
    depends_on:
      - proxy
      - cache
      - rabbit
      - postgres
    ports:
      - ':7001'
    environment:
      PORT: 7001
      NODE_ENV: docker
      DD_ENV: docker
      DD_SERVICE: cold-api
      REDISCLOUD_URL: redis://host.docker.internal:6379
      RABBITMQ_URL: amqp://guest:guest@rabbit:5672
      DATABASE_URL: postgres://postgres:postgres@host.docker.internal:5432/colddb
      LOG_FORMAT: pretty
    volumes:
      - /usr/src/app/node_modules
      - .:/repo
      - ~/.aws:/root/.aws
volumes:
  n8n_data:
  traefik_data:


