version: '3.8'
networks:
  cold:
    external: true
services:
  proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.10
    networks:
      - cold
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "-api.insecure=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.tcp.address=:5432"
      - "--entryPoints.tcp.address=:5672"
      - "--entryPoints.tcp.address=:15672"
      - "--entryPoints.tcp.address=:6379"
      - "--entryPoints.udp.address=:6379"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.rule=Host(`www.coldclimate.local`)"
      - "traefik.http.routers.proxy.entrypoints=web"
      - "traefik.entryPoints.web.address=:80"
      - "traefik.entryPoints.websecure.address=:443"
      - "traefik.entryPoints.tcp.address=:5432"
    ports:
      - "80:80"
      - "443:443"
      - "4200:4200"
      - "4400:4400"
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  rabbit:
    labels:
      - "traefik.tcp.routers.rabbit.rule=Host(`rabbit.coldclimate.local`)"
      - "traefik.http.routers.rabbit.rule=Host(`rabbit.coldclimate.local`)"
      - "traefik.tcp.services.rabbit.loadbalancer.server.port=5672"
      - "traefik.http.services.rabbit.loadbalancer.server.port=15672"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cold
    depends_on:
      - proxy
    image: rabbitmq:3-management-alpine
    container_name: cold-rabbit
  cache:
    labels:
      - "traefik.tcp.routers.redis.rule=Host(`cache.coldclimate.local`)"
      - "traefik.tcp.services.redis.loadbalancer.server.port=6379"
      - "traefik.udp.services.redis.loadbalancer.server.port=6379"
    image: redis:latest
    container_name: cold-cache
    restart: always
    depends_on:
      - proxy
    networks:
      - cold
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
  postgres:
    container_name: cold-postgres
    image: postgres:14-alpine
    labels:
      - "traefik.http.routers.postgres.rule=Host(`db.coldclimate.local`)"
      - "traefik.tcp.services.postgres.loadbalancer.server.port=5432"
      - "traefik.udp.services.postgres.loadbalancer.server.port=5432"
    depends_on:
      - proxy
    networks:
      - cold
    ports:
      - '5432:5432'
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=colddb
  graphql:
    build:
      context: .
      dockerfile: _graphql.dockerfile
      args:
        DD_ENV: docker
        NODE_ENV: docker
        DD_SERVICE: cold-graphql
        DATABASE_URL: postgres://postgres:postgres@postgres:5432/colddb
    container_name: cold-graphql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.graphql.rule=Host(`graphql.coldclimate.local`)"
      - "traefik.http.routers.graphql.entrypoints=web"
    restart: always
    networks:
      - cold
    links:
      - postgres
      - cache
    external_links:
      - postgres
      - cache
    depends_on:
      - proxy
      - postgres
    ports:
      - '9001:9001'
    environment:
      AUTH_BASE_URI: http://localhost:9001
      DD_SERVICE: cold-graphql
      AUTH_JWKS_URI: https://dev-6qt527e13qyo4ls6.us.auth0.com/.well-known/jwks.json
      AUTH_JWT_ALGORITHM: RS256
      AUTH_WHITELIST_DOMAINS: localhost
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/colddb
      NODE_ENV: docker
      DD_ENV: docker
      VITE_AUTH_CLIENT_ID: 7AtWz1WzXMty9QN38zrkfUj2JqxqpiFI
      VITE_AUTH_ZERO_DOMAIN: dev-6qt527e13qyo4ls6us.auth0.com
      AWS_REGION: us-east-1
    volumes:
      - ~/.aws:/root/.aws
  api:
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    build:
      context: .
      dockerfile: _api_local.dockerfile
      args:
        NODE_ENV: docker
        DD_ENV: docker
        DD_SERVICE: cold-api
        DD_VERSION: 99.99.99
        DATABASE_URL: postgres://postgres:postgres@host.docker.internal:5432/colddb
        DD_POSTGRES_PASSWORD: emanate-rail-pliable-brindled-plea-PADDOCK
        DD_API_KEY: ${DD_API_KEY}
        FC_GIT_COMMIT_SHA: cdc3b19
    container_name: cold-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.coldclimate.local`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.entryPoints.web.address=:80"
    restart: always
    networks:
      - cold
    links:
      - postgres
      - rabbit
      - cache
    external_links:
      - postgres
      - rabbit
      - cache
    depends_on:
      - proxy
      - cache
      - rabbit
      - postgres
    ports:
      - ':7001'
    environment:
      PORT: 7001
      NODE_ENV: docker
      DD_ENV: docker
      DD_SERVICE: cold-api
      REDISCLOUD_URL: redis://host.docker.internal:6379
      RABBITMQ_URL: amqp://guest:guest@rabbit:5672
      DATABASE_URL: postgres://postgres:postgres@host.docker.internal:5432/colddb
      LOG_FORMAT: pretty
    volumes:
      - /usr/src/app/node_modules
      - .:/repo
      - ~/.aws:/root/.aws


