version: '3.8'
networks:
  cold:
    external: true
services:
  api:
    build:
      context: .
      dockerfile: _platform.dockerfile
      args:
        NODE_ENV: development
        DD_SERVICE: cold-api
        DD_VERSION: 99.99.99
        DD_POSTGRES_PASSWORD: emanate-rail-pliable-brindled-plea-PADDOCK
        DD_API_KEY: ${DD_API_KEY}
        FC_GIT_COMMIT_SHA: cdc3b19
    container_name: cold-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.coldclimate.wtf`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.entryPoints.web.address=:80"
    restart: always
    networks:
      - cold
    external_links:
      - postgres
      - rabbit
      - cache
    depends_on:
      - cache
      - rabbit
      - postgres
    ports:
      - '7001:7001'
    environment:
      PORT: 7001
      NODE_ENV: development
      DD_SERVICE: cold-api
      LOG_FORMAT: pretty
    volumes:
      - /usr/src/app/node_modules
  climatiq:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.climatiq.rule=Host(`climatiq.coldclimate.wtf`)"
      - "traefik.http.routers.climatiq.entrypoints=web"
    build:
      context: .
      dockerfile: _platform.dockerfile
      args:
        NODE_ENV: development
        DD_SERVICE: cold-platform-climatiq
        DD_VERSION: 0.0.1
        LOG_FORMAT: pretty
        PORT: 7002
    container_name: cold-platform-climatiq
    restart: always
    networks:
      - cold
    external_links:
      - api
      - rabbit
      - cache
    depends_on:
      - api
    ports:
      - '7002:7002'
    environment:
      PORT: 7002
      DD_SERVICE: cold-platform-climatiq
      NODE_ENV: development
      LOG_FORMAT: pretty
    volumes:
      - /usr/src/app/node_modules
  openai:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`openai.coldclimate.wtf`)"
      - "traefik.http.routers.api.entrypoints=web"
    build:
      context: .
      dockerfile: _platform.dockerfile
      args:
        NODE_ENV: development
        DD_SERVICE: cold-platform-openai
        DD_VERSION: 0.0.1
        PORT: 7003
    container_name: cold-platform-openai
    restart: always
    networks:
      - cold
    external_links:
      - postgres
      - rabbit
      - cache
    depends_on:
      - proxy
      - api
      - cache
      - rabbit
      - postgres
      - climatiq
    ports:
      - '7003:7003'
    environment:
      PORT: 7003
      DD_SERVICE: cold-platform-openai
      DD_API_KEY: ${DD_API_KEY}
      NODE_ENV: development
      LOG_FORMAT: pretty
    volumes:
      - /usr/src/app/node_modules
  bayou:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.climatiq.rule=Host(`bayou.coldclimate.wtf`)"
      - "traefik.http.routers.climatiq.entrypoints=web"
    build:
      context: .
      dockerfile: _platform.dockerfile
      args:
        NODE_ENV: development
        DD_SERVICE: cold-platform-bayou
        DD_VERSION: 0.0.1
        PORT: 7004
        DD_API_KEY: ${DD_API_KEY}
        FC_GIT_COMMIT_SHA: cdc3b19
    container_name: cold-platform-bayou
    restart: always
    networks:
      - cold
    external_links:
      - api
      - rabbit
      - cache
    depends_on:
      - api
      - climatiq
    ports:
      - '7004:7004'
    environment:
      PORT: 7004
      DD_API_KEY: ${DD_API_KEY}
      DD_SERVICE: cold-platform-bayou
      NODE_ENV: development
      LOG_FORMAT: pretty
    volumes:
      - /usr/src/app/node_modules
  cache:
    labels:
      - "traefik.http.routers.cache.rule=Host(`cache.coldclimate.wtf`)"
      - "traefik.tcp.services.cache.loadbalancer.server.port=6379"
      - "traefik.udp.services.cache.loadbalancer.server.port=6379"
    image: redis:6.2-alpine
    container_name: cold-cache
    restart: always
    depends_on:
      - proxy
    networks:
      - cold
    ports:
      - '6379:6379'
    command: openai-server --save 20 1 --loglevel warning

  postgres:
    container_name: cold-postgres
    image: postgres:14-alpine
    depends_on:
      - proxy
    networks:
      - cold
    ports:
      - '5432:5432'
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=colddb
  rabbit:
    labels:
      - "traefik.http.routers.rabbit.rule=Host(`rabbit.coldclimate.wtf`)"
      - "traefik.tcp.services.rabbit.loadbalancer.server.port=5672"
      - "traefik.http.services.rabbit.loadbalancer.server.port=15672"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cold
    depends_on:
      - proxy
    image: rabbitmq:3-management-alpine
    container_name: cold-rabbit

