name: ğŸ“¸ Chromatic
on:
  workflow_dispatch:
  pull_request:
    branches:
      - staging
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.GH_TOKEN }}
  CACHE_NAME: cache-node-modules
  PR_NUMBER: ${{ github.event.number }}
  API_ADMIN_EMAIL: ${{ secrets.API_ADMIN_EMAIL }}
  API_ADMIN_PASSWORD: ${{ secrets.TEST_API_ADMIN_PASSWORD }}
  AUTH0_AUDIENCE: ${{ secrets.TEST_AUTH0_AUDIENCE }}
  AUTH0_CLIENT_ID: ${{ secrets.TEST_AUTH0_CLIENT_ID }}
  AUTH0_CLIENT_SECRET: ${{ secrets.TEST_AUTH0_CLIENT_SECRET }}
  AUTH0_ORG_ID: ${{ secrets.TEST_AUTH0_ORG_ID }}
  AUTH0_TOKEN_URL: ${{ secrets.TEST_AUTH0_TOKEN_URL }}
  API_SERVER_URL: ${{ github.event.deployment_status.target_url }}

jobs:
  pre_build:
    name: ğŸ¤”Cancel Duplicate Actions
    continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: 'outdated_runs'
          paths_ignore: '["**/README.md", "**/docs/**"]'
          do_not_skip: '["pull_request", "workflow_dispatch"]'
  chromatic-deployment:
    needs: pre_build
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: ğŸ§‘â€ğŸ’» Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0"
      - name: ğŸª¢ Install Yarn
        run: corepack enable && yarn set version 4.4.1
      - name: ğŸ’¼ Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}
      - name: ğŸ§© Install Dependencies
        # ğŸ‘‡ If cache not found, install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn
        # ğŸ‘‡ Adds Chromatic as a step in the workflow
      - name: ğŸ‘ Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          skip: 'dependabot/**' # ğŸ‘ˆ Skip dependabot PRs
          exitOnceUploaded: true,
          onlyChanged: true # ğŸ‘ˆ Required option to enable TurboSnap
          autoAcceptChanges: "main" # ğŸ‘ˆ Option to accept all changes on main
          # ğŸ‘‡ Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          externals: /(public|.storybook|tailwind.config.js)/**
        env:
          STORYBOOK_API_URL: ${{ secrets.STORYBOOK_API_URL }}
          NODE_OPTIONS: "--max_old_space_size=4096"
      - name: ğŸ Done!
        run: echo "ğŸ‘ Published Build To Chromatic"
