on: [push]

name: Datadog Software Composition Analysis

jobs:
  software-composition-analysis:
    runs-on: ubuntu-latest
    name: Datadog SBOM Generation and Upload
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Check imported libraries are secure and compliant
        id: datadog-software-composition-analysis
        uses: DataDog/datadog-sca-github-action@main
        with:
          datadog-hostname: api.us5.datadoghq.com
          dd_api_key: ${{ secrets.DATADOG_API }}
          dd_app_key: ${{ secrets.DD_APP_KEY }}
          dd_service: cold-monorepo
          dd_env: ci
          dd_site: us5.datadoghq.com
