name: ‚èÆ E2E Tests ‚è≠
on:
  workflow_dispatch:
    inputs:
      api_url:
        description: 'API Server URL to run tests against'
        type: string
        default: 'https://api.coldclimate.online'
        required: true
  deployment_status:
    types: [completed, success]
env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  NODE_ENV: ci
  NODE_OPTIONS: "-r dd-trace/ci/init"
  DD_SITE: us5.datadoghq.com
  DD_CIVISIBILITY_AGENTLESS_ENABLED: true
  DD_API_KEY: ${{ secrets.DD_APP_KEY }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.GH_TOKEN }}
  CACHE_NAME: cache-node-modules
  PR_NUMBER: ${{ github.event.number }}
  API_ADMIN_EMAIL: ${{ secrets.API_ADMIN_EMAIL }}
  API_ADMIN_PASSWORD: ${{ secrets.TEST_API_ADMIN_PASSWORD }}
  AUTH0_AUDIENCE: ${{ secrets.TEST_AUTH0_AUDIENCE }}
  AUTH0_CLIENT_ID: ${{ secrets.TEST_AUTH0_CLIENT_ID }}
  AUTH0_CLIENT_SECRET: ${{ secrets.TEST_AUTH0_CLIENT_SECRET }}
  AUTH0_ORG_ID: ${{ secrets.TEST_AUTH0_ORG_ID }}
  AUTH0_TOKEN_URL: ${{ secrets.TEST_AUTH0_TOKEN_URL }}
  API_SERVER_URL: ${{ github.event.inputs.api_url || github.event.deployment_status.target_url }}

jobs:
  api-e2e:
    name: üî¨ API Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: üë®‚ÄçüíªSetup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0"
      - name: üì¶ Cache node modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: üß© Install dependencies
        run: yarn && yarn postinstall && yarn add -D dd-trace

      - name: üåà Generate Prisma Client
        run: yarn dlx nx run cold-nest-library:prisma-generate

      - name: üèó build development
        run: yarn prebuild && yarn dlx nx reset && yarn dlx nx run cold-api:build:development

      - name: ü©ª Run Tests
        run: DD_SITE=us5.datadoghq.com DD_API_KEY=${{secrets.DD_API_KEY}} DD_CIVISIBILITY_AGENTLESS_ENABLED=true NODE_OPTIONS="-r dd-trace/ci/init" DD_ENV=test DD_SERVICE=cold-api-nest-e2e nx run cold-api-e2e:e2e:ci

