name: ğŸŒˆ Sync Prisma & GraphQL
on:
  workflow_dispatch:
  push:
    paths:
      - 'libs/nest/prisma/schema.prisma'
permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for npm provenance
  actions: write
env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.GH_TOKEN }}
  CACHE_NAME: cache-node-modules
  PR_NUMBER: ${{ github.event.number }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
jobs:
  migrate-db:
    name: ğŸª¿Migrate Database Changes ğŸª¿
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'

      - name: Enable Corepack
        run: corepack enable

      - name: Use Yarn
        run: corepack prepare yarn@4.4.1 --activate

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Set DATABASE_URL
        run: echo "DATABASE_URL=$([[ $BRANCH_NAME == main* ]] && echo ${{ secrets.PRODUCTION_DATABASE_URL }} || echo ${{ secrets.STAGING_DATABASE_URL }})" >> $GITHUB_ENV

      - name: Install dependencies
        run: yarn install

      - name: Run Prisma Migrations
        run: yarn prisma migrate deploy

  sync-graphql:
    runs-on: ubuntu-latest
    name: ğŸ”„ Sync GraphQL Schema
    needs:
      - migrate-db
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'

      - name: Enable Corepack
        run: corepack enable

      - name: Install TS-NODE
        run: npm install -g ts-node

      - name: Use PNPM
        run: corepack prepare pnpm@9.8.0 --activate

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: 'apps/cold-graphql/node_modules'
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Set DATABASE_URL
        run: echo "DATABASE_URL=$([[ $BRANCH_NAME == main* ]] && echo ${{ secrets.PRODUCTION_DATABASE_URL }} || echo ${{ secrets.STAGING_DATABASE_URL }})" >> $GITHUB_ENV

      - name: Set PGSSLMODE
        run: echo "PGSSLMODE=no-verify" >> $GITHUB_ENV

      - name: Set DATABASE_NAME
        run: echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> $GITHUB_ENV

      - name: Set DATABASE_USERNAME
        run: echo "DATABASE_USERNAME=flightcontrol" >> $GITHUB_ENV
        # run: echo "DATABASE_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV

      - name: Set DATABASE_PASSWORD
        run: echo "DATABASE_PASSWORD=$([[ $BRANCH_NAME == main* ]] && echo '${{ secrets.PRODUCTION_DB_PASSWORD }}' || echo '${{ secrets.STAGING_DB_PASSWORD }}')" >> $GITHUB_ENV

      - name: Set DATABASE_HOST
        run: echo "DATABASE_HOST=$([[ $BRANCH_NAME == main* ]] && echo '${{ secrets.PRODUCTION_DB_HOST }}' || echo '${{ secrets.STAGING_DB_HOST }}')" >> $GITHUB_ENV

      - name: Set NODE_ENV
        run: echo "NODE_ENV=$([[ $BRANCH_NAME == main* ]] && echo production || echo staging)" >> $GITHUB_ENV

      - name: Install dependencies
        run: pnpm install
        working-directory: apps/cold-graphql

      - name: Sync â¡ğ“‡ğ“ªğ“¹ğ’½ğ“ ğ“› Changes
        run: pnpm sync
        working-directory: apps/cold-graphql

      - name: Configure ğŸ„¶ğŸ„¸ğŸ…ƒğŸ„·ğŸ…„ğŸ„±
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit Changes To ğŸ„¶ğŸ„¸ğŸ…ƒğŸ„·ğŸ…„ğŸ„±
        run: |
          git add .
          git commit -m "ci: sync prisma schema changes"

      - name: ğŸ«¸ Push Changes To ğŸ„¶ğŸ„¸ğŸ…ƒğŸ„·ğŸ…„ğŸ„±
        if: steps.PR.outputs.pr_found != 'true'
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          unprotect_reviews: true
          force: true
          timeout: 3
          acceptable_conclusions: success, failure, neutral, cancelled, skipped, timed_out, action_required
